### ISSUE TITLE
Labeling . Spots

### ISSUE THREAD

**Issue by teaSqr** [renemeye/jva-karte-frontend#1]
Die betreffenden Spots unter Labeling rausnehmen und umbennennen in "Spots".

![labeling_beispiele rausnehmen umbenennen in _spots](https://cloud.githubusercontent.com/assets/12716711/7965151/ec2f2b3e-0a1b-11e5-8fd5-707af04228e1.jpg)

**Comment by renemeye** [comment]
Punkte entfernt
