### ISSUE TITLE
Labeling - Hilfestellung 

### ISSUE THREAD

**Issue by teaSqr** [renemeye/jva-karte-frontend#2]
Im Hilfetext wird eindeutig auf OSM verwiesen.

Verbesserung:

"Mit diesem Editor kannst du die Karte der JVA vervollständigen und anderen Räume, Plätze,... zeigen.

Deine eingetragenen Informationen sind für jeden sichtbar."

![labeling_hilfeeinstellungen key h](https://cloud.githubusercontent.com/assets/12716711/7965194/3d74e02e-0a1c-11e5-918a-09a06178799f.jpg)

**Comment by renemeye** [comment]
done
